-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建壁纸分类表
CREATE TABLE categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(50) NOT NULL,
  type VARCHAR(20) NOT NULL, -- style/size/color
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建壁纸表
CREATE TABLE wallpapers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title VARCHAR(200) NOT NULL,
  description TEXT,
  category_id UUID REFERENCES categories(id),
  tags TEXT[],
  resolution VARCHAR(50),
  format VARCHAR(10) DEFAULT 'jpg',
  file_size INTEGER,
  storage_path TEXT,
  thumbnail_path TEXT,
  is_featured BOOLEAN DEFAULT false,
  is_recommended BOOLEAN DEFAULT false,
  is_published BOOLEAN DEFAULT true,
  download_count INTEGER DEFAULT 0,
  view_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建收藏表（基于浏览器缓存，这里仅做数据结构）
CREATE TABLE favorites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  wallpaper_id UUID REFERENCES wallpapers(id) ON DELETE CASCADE,
  user_session_id TEXT, -- 用于标识匿名用户会话
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(wallpaper_id, user_session_id)
);

-- 创建下载记录表
CREATE TABLE downloads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  wallpaper_id UUID REFERENCES wallpapers(id) ON DELETE CASCADE,
  user_session_id TEXT,
  downloaded_at TIMESTAMP DEFAULT NOW()
);

-- 创建广告配置表
CREATE TABLE ad_configs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  position VARCHAR(50) NOT NULL, -- banner/native_footer/download_incentive
  title VARCHAR(100),
  image_url TEXT,
  link_url TEXT,
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建管理员表
CREATE TABLE admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE wallpapers ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE downloads ENABLE ROW LEVEL SECURITY;
ALTER TABLE ad_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- 公开读取策略
CREATE POLICY "所有人可查看分类" ON categories FOR SELECT USING (true);
CREATE POLICY "所有人可查看已发布壁纸" ON wallpapers FOR SELECT USING (is_published = true);
CREATE POLICY "所有人可查看广告配置" ON ad_configs FOR SELECT USING (is_active = true);

-- 插入默认分类
INSERT INTO categories (name, type, sort_order) VALUES
('治愈系', 'style', 1),
('赛博朋克', 'style', 2),
('极简风', 'style', 3),
('古风', 'style', 4),
('动漫风', 'style', 5),
('自然风景', 'style', 6),
('手机壁纸', 'size', 7),
('电脑桌面', 'size', 8),
('平板壁纸', 'size', 9),
('4K超清', 'size', 10),
('深色系', 'color', 11),
('浅色系', 'color', 12),
('彩色系', 'color', 13),
('莫兰迪', 'color', 14);

-- 插入默认广告配置
INSERT INTO ad_configs (position, title, is_active, sort_order) VALUES
('banner', '顶部Banner广告', true, 1),
('native_footer', '底部原生广告', true, 2),
('download_incentive', '下载激励广告', true, 3);