-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

INSERT INTO storage.buckets (id, name, public) VALUES ('wallpapers', 'wallpapers', true) ON CONFLICT (id) DO NOTHING;

CREATE POLICY "允许所有人上传壁纸" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'wallpapers');
CREATE POLICY "允许所有人查看壁纸" ON storage.objects FOR SELECT USING (bucket_id = 'wallpapers');
CREATE POLICY "允许管理员删除壁纸" ON storage.objects FOR DELETE USING (bucket_id = 'wallpapers');