-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

DROP POLICY IF EXISTS "所有人可查看已发布壁纸" ON wallpapers;
CREATE POLICY "允许所有人查看已发布壁纸" ON wallpapers FOR SELECT USING (is_published = true);
CREATE POLICY "允许管理员管理壁纸" ON wallpapers FOR ALL USING (true);