-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建音乐表
CREATE TABLE IF NOT EXISTS public.musics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  artist TEXT NOT NULL,
  album TEXT,
  cover_url TEXT,
  audio_url TEXT NOT NULL,
  duration INTEGER,
  genre TEXT,
  play_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建壁纸表
CREATE TABLE IF NOT EXISTS public.wallpapers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT NOT NULL,
  thumbnail_url TEXT,
  category TEXT,
  tags TEXT[],
  resolution TEXT,
  download_count INTEGER DEFAULT 0,
  file_size BIGINT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建分类表
CREATE TABLE IF NOT EXISTS public.categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  type TEXT CHECK (type IN ('music', 'wallpaper')),
  icon TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建播放记录表（用于统计热门）
CREATE TABLE IF NOT EXISTS public.play_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  music_id UUID REFERENCES public.musics(id) ON DELETE CASCADE,
  played_at TIMESTAMP DEFAULT NOW(),
  ip_hash TEXT
);

-- 创建下载记录表
CREATE TABLE IF NOT EXISTS public.download_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  wallpaper_id UUID REFERENCES public.wallpapers(id) ON DELETE CASCADE,
  downloaded_at TIMESTAMP DEFAULT NOW(),
  ip_hash TEXT
);

-- 启用 RLS
ALTER TABLE public.musics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallpapers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.play_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.download_history ENABLE ROW LEVEL SECURITY;

-- 创建策略：所有人可查看内容
CREATE POLICY "所有人可查看音乐" ON public.musics FOR SELECT USING (true);
CREATE POLICY "所有人可查看壁纸" ON public.wallpapers FOR SELECT USING (true);
CREATE POLICY "所有人可查看分类" ON public.categories FOR SELECT USING (true);

-- 插入策略（匿名用户可记录播放和下载）
CREATE POLICY "所有人可记录播放" ON public.play_history FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可记录下载" ON public.download_history FOR INSERT WITH CHECK (true);

-- 创建存储桶
INSERT INTO storage.buckets (id, name, public) 
VALUES 
  ('music-covers', 'music-covers', true),
  ('music-audio', 'music-audio', true),
  ('wallpapers', 'wallpapers', true),
  ('wallpapers-thumb', 'wallpapers-thumb', true)
ON CONFLICT (id) DO NOTHING;

-- 创建索引优化查询
CREATE INDEX IF NOT EXISTS idx_musics_genre ON public.musics(genre);
CREATE INDEX IF NOT EXISTS idx_musics_play_count ON public.musics(play_count DESC);
CREATE INDEX IF NOT EXISTS idx_musics_created_at ON public.musics(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wallpapers_category ON public.wallpapers(category);
CREATE INDEX IF NOT EXISTS idx_wallpapers_download_count ON public.wallpapers(download_count DESC);
CREATE INDEX IF NOT EXISTS idx_wallpapers_created_at ON public.wallpapers(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_play_history_music_id ON public.play_history(music_id);
CREATE INDEX IF NOT EXISTS idx_download_history_wallpaper_id ON public.download_history(wallpaper_id);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_musics_updated_at BEFORE UPDATE ON public.musics
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_wallpapers_updated_at BEFORE UPDATE ON public.wallpapers
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();