-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 修复 storage 存储桶的 RLS 策略
-- 允许匿名用户上传文件到 wallpapers 存储桶
CREATE POLICY "允许匿名上传壁纸" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'wallpapers');
CREATE POLICY "允许匿名查看壁纸" ON storage.objects FOR SELECT USING (bucket_id = 'wallpapers');
CREATE POLICY "允许匿名删除壁纸" ON storage.objects FOR DELETE USING (bucket_id = 'wallpapers');