-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 删除旧策略
DROP POLICY IF EXISTS "所有人可查看分类" ON public.categories;

-- 创建新策略：允许匿名用户查看和插入分类
CREATE POLICY "允许匿名查看分类" ON public.categories FOR SELECT USING (true);
CREATE POLICY "允许匿名插入分类" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "允许匿名删除分类" ON public.categories FOR DELETE USING (true);