-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 修复 wallpapers 表的 RLS 策略
DROP POLICY IF EXISTS "所有人可查看壁纸" ON public.wallpapers;

-- 创建新策略：允许匿名用户查看和插入壁纸
CREATE POLICY "允许匿名查看壁纸" ON public.wallpapers FOR SELECT USING (true);
CREATE POLICY "允许匿名插入壁纸" ON public.wallpapers FOR INSERT WITH CHECK (true);
CREATE POLICY "允许匿名删除壁纸" ON public.wallpapers FOR DELETE USING (true);